apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-slave
  labels:
    app: redis
    role: slave
spec:
  replicas: 2
  selector:
    matchLabels:
      app: redis
      role: slave
  template:
    metadata:
      labels:
        app: redis
        role: slave
    spec:
      containers:
      - name: redis-slave
        image: ibmcom/guestbook-redis-slave:v2
        env:
        - name: REDIS_MASTER_SERVICE_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: redis_pass
              name: guestbook-config
        args: ["--masterauth ", "$(REDIS_MASTER_SERVICE_PASSWORD)", "--slaveof", "redis-master", "6379"]
        ports:
        - name: redis-server
          containerPort: 6379
