apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-master
  labels:
    app: redis
    role: master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
      role: master
  template:
    metadata:
      labels:
        app: redis
        role: master
    spec:
      containers:
      - name: redis-master
        image: redis:3.2.9
        env:
        - name: REDIS_MASTER_SERVICE_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: guestbook-config
              key: redis_pass
        args: ["--requirepass", "$(REDIS_MASTER_SERVICE_PASSWORD)"]
        ports:
        - name: redis-server
          containerPort: 6379
